var language = {
		eng : {
			country : 'Country',
			state : 'State',
			city : 'City',
			street : 'Street',
			selectDataInterval : 'Select Time Interval',
			multipicker : {
				dateFormat: "yy-mm-dd",
				dayNames: ['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'],
			    dayNamesMin: ['S','M','T','W','T','F','S','S'],
			    dayNamesShort: ['Su','Mo','Tu','We','Th','Fr','Sa','Su'],
			    monthNames: ['January','February','March','April','May','June','July','August','September','October','November','December'],
			    monthNamesShort: ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'],
			    nextText: 'Next',
			    prevText: 'Previous'
			},
			radius : 'Radius (meters)',
			filter : 'Filter',
			log : 'Graph',
			searching: 'Searching...',
			day : 'Day',
			devices : 'Devices',
			points : 'Points',
			averageSpeed : 'Avg Speed',
			dataReference : 'Data for Reference',
			dataAnalysis : 'Data for Analysis',
			radiusError: 'Please type a valid radius value!',
			logError: 'No data for this search!'
		},
		ptb : {
			country : 'País',
			state : 'Estado',
			city : 'Cidade',
			street : 'Rua',
			selectDataInterval : 'Selecionar Período',
			multipicker : {
				dateFormat: "yy-mm-dd",
				dayNames: ['Domingo','Segunda','Terça','Quarta','Quinta','Sexta','Sábado'],
			    dayNamesMin: ['D','S','T','Q','Q','S','S','D'],
			    dayNamesShort: ['Dom','Seg','Ter','Qua','Qui','Sex','Sáb','Dom'],
			    monthNames: ['Janeiro','Fevereiro','Março','Abril','Maio','Junho','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro'],
			    monthNamesShort: ['Jan','Fev','Mar','Abr','Mai','Jun','Jul','Ago','Set','Out','Nov','Dez'],
			    nextText: 'Próximo',
			    prevText: 'Anterior'
			},
			radius : 'Raio (metros)',
			filter : 'Filtrar',
			log : 'Gráfico',
			searching: 'Buscando...',
			day : 'Dia',
			devices : 'Dispositivos',
			points : 'Pontos',
			averageSpeed : 'Vel. Média',
			dataReference : 'Dados de Referência',
			dataAnalysis : 'Data de Análise',
			radiusError: 'Digite um raío válido!',
			logError: 'Busca sem dados!'
		}
}